# Generated by Django 4.2.1 on 2023-12-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='identify_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='identify_type',
            field=models.CharField(choices=[('national_id_card', 'National_ID_Card'), ('drivers_licence', 'Driver_Licence'), ('international_passport', 'International Passport')], max_length=140),
        ),
    ]
