# Generated by Django 4.2.1 on 2023-12-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_identify_image_kyc_identity_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='kyc'),
        ),
    ]
