# Generated by Django 4.2.1 on 2023-12-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
    ]
