# Generated by Django 4.2.1 on 2023-12-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_account_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='marrital_status',
            new_name='marital_status',
        ),
    ]
