# Generated by Django 4.2.1 on 2023-12-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_marrital_status_kyc_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='marital_status',
            field=models.CharField(default='Single', max_length=40, verbose_name=(('married', 'Married'), ('single', 'Single'), ('other', 'Other'))),
        ),
    ]
