# Generated by Django 4.2.1 on 2023-12-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_kyc_date_of_birth_alter_kyc_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('in-active', 'In-active'), ('pending', 'Pending')], default='In-active', max_length=100),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('single', 'Single'), ('other', 'Other')], max_length=40),
        ),
    ]
