# Generated by Django 5.0.1 on 2024-02-11 09:59

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_account_pin_number_pin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pin_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=7, prefix='', unique=True),
        ),
        migrations.DeleteModel(
            name='Pin_Number',
        ),
    ]
